# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly

matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
#script: #don't use default script; need inline=no to get coverage correct; see https://github.com/JuliaLang/Pkg.jl/pull/870
#  - julia --check-bounds=yes --inline=no -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
jobs:
  include:
    - stage: "Documentation"
      os: linux
      addons:
        apt:
          packages:
            - libqt5widgets5
            - texlive
            - dvipng
      julia: 1.0
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate();
                                    Pkg.build("ARCHModels")' #https://github.com/JuliaLang/Pkg.jl/issues/862
        - julia --project=docs/ docs/make.jl
      after_success: skip
