# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
codecov: true
coveralls: true
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      os: linux
      addons:
        apt:
          packages:
            - libqt5widgets5
            - texlive
            - dvipng
      julia: 1.0
      script:
        - julia --project=docs/ -e 'using Pkg;
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate();
                                    Pkg.build("ARCHModels")' #https://github.com/JuliaLang/Pkg.jl/issues/862
        - julia --project=docs/ docs/make.jl
      after_success: skip
